### ISSUE TITLE
Correções e Padronizações 

### ISSUE THREAD

**Issue by MaxPresi** [MaxPresi/FalloutNewVegas_BR#1]
- [x] Courier > Entregador > Mensageiro
- [x] Datura (Estramônio)
- [x] Tuscon > Tucson
- [x] turpentine > aguarrás
- [x] Minta (Mentir) - Ataque (Atacar) - FALHA(Fracasso)
- [x] Gangue da pólvora (Arruaceiros da Pólvora)
- [x] God(God) - Dog(Dog)
- [x] Joshua(Josué) - Elias(Elijah)
- [x] Bark Scorpions
- [x] lt.(Ten.) sgt.(Sarg.) col.(Cel.) capt.(Cap.) Cpl.(Cb.) Pvt.(Sd.)
- [x] Caravana Vermelha(Caravana Carmesim)
- [x] Atomic Wrangler(Vaqueiro Atômico)
- [x] Fallows-Chalk(Segue-Giz)
- [x] Sorrows(Aflitos)
- [x] Pinto Bean(Feijão Carioquinha)
- [x] Father (Padre? Pai?)
- [x] back when > Os Antigos
- [x] exit to: Sair para
- [x] The Sink (Lugar) - O Algar
- [x] Sink (NPC) - Pia
- [x] siar > sair
- [x] woozy - meio bobo
- [x] riot gear - anti-motim - tropa de choque
- [x] power armor - power helmet
- [x] waking cloud - Nuvem Vigilante - Corrigir gênero para feminino
- [x] fita holografica > holofita
- [x] dead horse > Cavalos Mortos
- [x] Tiny Tots - Pequeninos
- [x] Collar - Colar - Coleira
- [x] outfit - traje > Roupa
- [x] scrubs - Bata
- [x] happy trails - Trilhas Felizes
- [x] trapper - armadilheiro
- [x] Hologram Vendor - Comerciante Holográfico
- [x] mr handy - sr útil, mr gutsy - Sr Corajoso
- [x] Pre-War bills > Notas Pré-Guerra
- [x] Estrela - Starlet > Estrela
- [x] Begin again, but know when to let go. > ?
- [x] Superstims 
- [x] NVDLC01ChristineDialogueNVDLC01ChristineTopic125
- [x] NVDLC01DogDialogueNVDLC01DogTopic080
- [x] NVDLC01DogDialogueNVDLC01GodTopic035
- [x] Second Level/Nível Dois -> Segundo Andar
- [x] Intercomunicador -> Interfone
- [x] Taboo/Tabu -> Interdição -> Tabu
- [x] Great Salt Lake\Grande Lago Salgado -> Great Salt Lake
- [x] Great Staircase
- [x] Eastern Virgin -  Virgem do Leste -> Virgin do Leste
- [x] CIU - UCI
- [x] AVHunger
- [x] AVSleepDeprevation
- [x] Saturnite - Saturnino
- [x] Muggy - Canequinha
- [x] think tank - Labgoratório de Idéias
- [x] honey mesquite (Prosopis glandulosa) - Algaroba Mel(?) 
- [x] Cyberdog - Cibercão -> Cybercão
- [x] cattle prods > Aguilhão
- [x] Trauma Harness - Arreio de Trauma - Armadura de Trauma
- [x] Think Tank (Lugar) - Laboratório de Idéias / Think Tank (robôs)- Tanque de Pensamentos
- [x] Lou (liu - Liutenant) - Tim (tem - tenente)
- [x] Divide > Divisão > Divisória
- [x] Scavenger / scavengers > ?
- [x] satchel charges > ?
- [x] NVDLC04UlyssesBigMT1HolotapeNote [0400CD61] -> YUP Bug? (FNVEdit) 
- [x] NVDLC04UlyssesWhiteLegs2HolotapeNote[0400CD67] -> YUP Bug? (FNVEdit) 
- [x] NVDLC04UlyssesBigMT3HolotapeNote[0400CD69]  -> YUP Bug? (FNVEdit) 
- [x] NVDLC04UlyssesFinalMsgHolotape[0400CD8E] -> YUP Bug? (FNVEdit) 
- [x] NVDLC04UlyssesWhiteLegs3Holotape[0400CD91] -> YUP Bug? (FNVEdit) 
- [x] NVDLC04DialogueEDENVDLC04EDETopic079[0400D2BF]  -> YUP Bug? (FNVEdit) 
- [x] Long 15 - Longos 15
- [x] set off > disparar
- [x] bighorn bluff
- [x] Li'l Scout Lunchbox > Lancheira do Pequeno Escoteiro
- [x] Vespa > Cazador
- [x] Salient Green > Creme Verde
- [x] Fiends > ?

**Comment by andremeireles** [comment]
Fico feliz em saber que ainda existem pessoas dedicando-se a este jogo.
Descobri FO:NV recentemente e comecei a traduzir alguns modificadores pra uso próprio e pública-los quando estiver concluído. Tenho apenas um modificador publicado no nexus/skyrim.

Gostaria de saber duas coisas de você.

Existe uma forma de o jogo exibir caracteres que possuem o til (ã, õ) ?

Você pretende localizar as palavras wasteland, wastelander, fiends, raider, etc?

No modificador "More Perks", traduzi Mojave Wasteland pra Deserto de Mojave, mas ainda não estudei sobre como chamar wastelanders, visto que cada deserto possui um nome diferente pra seus moradores. Provavelmente sejam os Navarros, mas ainda não estou seguro disso.

**Comment by MaxPresi** [comment]
> Fico feliz em saber que ainda existem pessoas dedicando-se a este jogo.
> Descobri FO:NV recentemente e comecei a traduzir alguns modificadores pra uso próprio e pública-los quando estiver concluído. Tenho apenas um modificador publicado no nexus/skyrim.
> 
> Gostaria de saber duas coisas de você.
> 
> Existe uma forma de o jogo exibir caracteres que possuem o til (ã, õ) ?
> 

Nunca tive problemas em exibir acentos dentro do jogo, não sei se isso é do jogo ou vem com algum dos mods de patch não oficial.
> Você pretende localizar as palavras wasteland, wastelander, fiends, raider, etc?
> 
> No modificador "More Perks", traduzi Mojave Wasteland pra Deserto de Mojave, mas ainda não estudei sobre como chamar wastelanders, visto que cada deserto possui um nome diferente pra seus moradores. Provavelmente sejam os Navarros, mas ainda não estou seguro disso.

Wasteland está mais para Ermos (fallout 4) ou Terras baldias (Cyberpunk 2077), mas eu não sei. Eu comecei com a ideia de traduzir tudo, mas atualmente eu desisti. As traduções originais da GameVicio não fazia, então eu pretendo não fazer. No máximo estou corrigindo uma série de termos traduzidos errados, mas não pretendo fazer mais que isso.
Não por agora
Tanto pro 3 quanto pro NV eu ainda pretendo fazer uma padronizada no estilo do 4, traduzindo tudo, que acho que ficaria melhor pra quem entrar na franquia pelo 4, mas só depois de terminar essa. Será mais fácil tbm, é só traduzir as palavras.

Ainda sim não sei o que fazer com alguns nomes de gangues e lugares. Traduzir nome de cidade é complicado.

**Comment by andremeireles** [comment]
Provavelmente seja alguma configuração que desconheço.
Imagino que seja muito trabalho para uma só pessoa.
Caso precise de ajuda, não hesite em criar tópico. Com certeza aparecerão pessoas interessadas.

**Comment by RicardoRamosWorks** [comment]
Wasteland o termo popular que mais chega perto é Deserto (nós usamos deserto para designar algo como wasteland), as demais definições são formais e antigas, estão em desuso, vc não vê nem no meio jurídico... O nome dos lugares e das gangues, é mais a designação literal do que é, do que um nome. Tipo os raiders, que a tradução seria invasores. Mas os caras são uma especie de punks, desordeiros, raider estaria mais para o que chamamos de bandido, meliante.

**Comment by MaxPresi** [comment]
Eu pretendo manter algumas coisas sem tradução como na Game Vicio, pq o pessoal se acostumou assim.
Ainda pretendo fazer uma estilo Fallout 4 depois, bem depois
