### ISSUE TITLE
Sem Texto na Title Screen

### ISSUE THREAD

**Issue by PugPugnaz** [MaxPresi/FalloutNewVegas_BR#11]
Com licença mas eu tenho instalado todos os requerimentos do mod mas quando eu abro o jogo a tela de título não tem texto, os botões ainda estão lá mas todo o texto sumiu, eu testei e ela ainda aparece quando eu desabilito a tradução, existe alguma forma de resolver isto?

**Comment by MaxPresi** [comment]
Foi mal a demora pra responder, mas vc conseguiu resolver?

**Comment by MaxPresi** [comment]
Provavelmente um problema de textura. Editou o ini mas não colocou a pasta texutre,
