### ISSUE TITLE
Atualiza a tradução

### ISSUE THREAD

**Issue by OsmarTelo** [MaxPresi/FalloutNewVegas_BR#13]
O jogo teve uma atualização e fica dando crash quando instala. isso acontece logo no começo do jogo e é o unico que traduz as dlcs fora o erro dos acentos.

**Comment by MaxPresi** [comment]
atualizei a tradução. vou testar tudo e se estiver tudo certo, posto lá no Nexus. Desculpa o sumiço kkkkk

**Comment by MaxPresi** [comment]
Resolvido
