### ISSUE TITLE
Personagens com texturas de cabeça e corpo diferente

### ISSUE THREAD

**Issue by n1rmic** [MaxPresi/FalloutNewVegas_BR#14]
Entao, basicamente meu fallout é so com a mod list do Viva new vegas, porem adicionei 3 mods de pack de armas. E os personagens ficam com cores mescladas do tipo: Cabeça branca e corpo negro.
![20240527174157_1](https://github.com/MaxPresi/FalloutNewVegas_BR/assets/70639607/f6657038-7622-4b5e-9654-a11b3b0ae4b5)

**Comment by CamaleaoFormal** [comment]
esse problema não tem relação com outros mods e sim com a tradução, aconteceu comigo tbm. Eu precisei entrar nos arquivos do jogo e modificar umas infos, se eu encontrar aqui e te mando ( faz tempo que resolvi todos os problemas desse Mod ).

**Comment by MaxPresi** [comment]
eu to jogando e catando todas as ocorrências pra resolver. se puder ajudar, abre o console (tecla ' ) clica no NPC e me manda o ID dos que vc encontrar. não faço ideia do pq ta acontecendo isso kkkkkk

**Comment by MaxPresi** [comment]
Resolvido na ultima atualização, 2.0 lá no Nexus. Agora tem um ESP separados só pros NPCs, igual o YUP, pra não ter esse problema.
