### ISSUE TITLE
Erro com o DarNified UI ou eu sou burro.

### ISSUE THREAD

**Issue by JoaoManoelSilvaMorais** [MaxPresi/FalloutNewVegas_BR#3]
Eu instalei o YUP, sua tradução e o DarNified UI, mas ainda não consigo ver os "ã" e também as palavras parecem estar fora de seu lugar, tanto que o "Sair" está pela metade. Eu não sei se eu instalei o DarNified UI certo, eu tentei baixar aquele DarNified UI Font Dummies mas o jogo só crashou no menu, então eu tirei o mesmo.

![122693161-0975f580-d20f-11eb-925c-72af7a82b4bf](https://user-images.githubusercontent.com/85969033/122693328-c2d4cb00-d20f-11eb-9f97-c8196f4f9200.png)

![image](https://user-images.githubusercontent.com/85969033/122693767-a89bec80-d211-11eb-8f26-e243fad2b682.png)

**Comment by MaxPresi** [comment]
Vc não instalou as fontes do DarNified UI corretamente, por isso tá tudo fora do lugar e sem ã. Tem que editar o .indo ou usar um mod pra isso. Só olhar lá na página do DarNified UI, é a última linha do primeiro tópico.

Desculpa não ajudar mais, mas tô pelo celular e ele tá uma bosta kkkkkk

**Comment by JoaoManoelSilvaMorais** [comment]
![image](https://user-images.githubusercontent.com/85969033/122758914-be3fff00-d26f-11eb-9614-c1c6b45a2703.png)

O Erro agora é outro...

**Comment by MaxPresi** [comment]
Cara, continua sendo erro da DarNified UI. Alguma configuração que vc tá fazendo errada.

**Comment by JoaoManoelSilvaMorais** [comment]
> Cara, continua sendo erro da DarNified UI. Alguma configuração que vc tá fazendo errada.

Sim, eu vou tentar arrumar, se eu não conseguir eu vou jogar sem acentos msm xD.
Perguntinha, os outros fixes além do YUP são necessários ou são opcionais?

**Comment by JoaoManoelSilvaMorais** [comment]
Deixa, acabei de corrigir, eu usei o mod [DarNified UI Font Dummies](https://www.nexusmods.com/newvegas/mods/63560/?) e o nexus mod estava configurado errado, então eu usei o metodo de Hardlink Deployment que consertou tudo.

**Comment by MaxPresi** [comment]
Estranho pq eu usei essa mod pra fazer os teste, pq tava com preguiça de ficar mexendo em INI só pra testar kkkkk
Mas que bom que deu certo
