### ISSUE TITLE
easy pete

### ISSUE THREAD

**Issue by pedricaro10** [MaxPresi/FalloutNewVegas_BR#4]
olá tem um erro na linha de dialogo do easy pete
![enb2021_6_20_23_40_32](https://user-images.githubusercontent.com/55963950/122700339-785c4a00-d221-11eb-9fc5-f4b4af574a3b.png)
toda ela toda cadeia de dialogo relocinado ao benny

**Comment by MaxPresi** [comment]
Vou dar.uma olhada mais tarde

**Comment by MaxPresi** [comment]
Vc tá usando os outros patchs? Eu percebi que eu subi o arquivo errado do Asterra's Many Fix. Upei o sem tradução kkkkkkk
Estou corrigindo isso e já posto o arquivo certo.

**Comment by MaxPresi** [comment]
Pronto. Atualizei o Asterra's Many Fixes, deve resolver o problema. Atualizei o YUP e a base também. baixa todos, testa e me avisa se resolveu.

**Comment by JoaoManoelSilvaMorais** [comment]
> Pronto. Atualizei o Asterra's Many Fixes, deve resolver o problema. Atualizei o YUP e a base também. baixa todos, testa e me avisa se resolveu.

O problema deve ser no jogo dele, pq aqui está traduzido

![image](https://user-images.githubusercontent.com/85969033/122780193-01589d00-d285-11eb-8fde-22531a5954b6.png)

**Comment by MaxPresi** [comment]
Ele deve usar o mod do Asterra, que eu subi o arquivo errado, mas corrigi já

**Comment by pedricaro10** [comment]
Sim obrigado
