### ISSUE TITLE
Partes não traduzidas que eu encontrar

### ISSUE THREAD

**Issue by JoaoManoelSilvaMorais** [MaxPresi/FalloutNewVegas_BR#5]
Aqui eu só vou colocar alguns lugares que eu encontrar não traduzidos.

Nota: Não irei colocar nomes de itens, apenas diálogos, missões e notas.

Mods usados por mim:
![image](https://user-images.githubusercontent.com/85969033/122779552-5b0c9780-d284-11eb-99a2-a46333863f14.png)

Tutorial sobre Aparência:
![image](https://user-images.githubusercontent.com/85969033/122779613-6b247700-d284-11eb-8168-26edb4a0b5ee.png)

Final da fala da Sunny Smiles, depois de falar que o médico te mandou ver ela:
![image](https://user-images.githubusercontent.com/85969033/122780980-bf7c2680-d285-11eb-8607-86c9a953fe9b.png)

Final da missão de matar os Geckos nos poços de Goodsprings
![image](https://user-images.githubusercontent.com/85969033/122782667-4978bf00-d287-11eb-9ad1-a9c8227baee8.png)

Esse pode dar uma desconsiderada pq é só a cabana do Victor :/
![image](https://user-images.githubusercontent.com/85969033/122783230-c0ae5300-d287-11eb-871e-416d7b2b47ca.png)

Eu vou colocar o mod [OneTweak for FNV](https://www.nexusmods.com/newvegas/mods/59266) para corrigir o erro de alt+tab e tbm o mouse duplicado

Fala da Trudy depois de perguntar se Goodsprings recebe muitos visitantes:
![image](https://user-images.githubusercontent.com/85969033/122790081-5947d180-d28e-11eb-8704-bb7227ad6e95.png)

De novo uma fala da Trudy, agora é quando pergunta sobre a discussão dela com aquele arruaceiro da pólvora:
![image](https://user-images.githubusercontent.com/85969033/122790365-a1ff8a80-d28e-11eb-85bc-04aa183bf5ef.png)

Ta bom, quase todas as falas da Trudy estão em inglês

**Comment by MaxPresi** [comment]
Cara, estão traduzidas aqui pra mim. Da uma olhada na ordem dos mods, pode ser que o YUP original esteja na frente da tradução.

> Final da fala da Sunny Smiles, depois de falar que o médico te mandou ver ela:
> ![image](https://user-images.githubusercontent.com/85969033/122780980-bf7c2680-d285-11eb-8607-86c9a953fe9b.png)
![image](https://user-images.githubusercontent.com/34844981/122792989-11767980-d291-11eb-8d3f-50501c8452d7.png)

> Fala da Trudy depois de perguntar se Goodsprings recebe muitos visitantes:
> ![image](https://user-images.githubusercontent.com/85969033/122790081-5947d180-d28e-11eb-8704-bb7227ad6e95.png)
![image](https://user-images.githubusercontent.com/34844981/122792604-b17fd300-d290-11eb-9fe3-a06d19a49643.png)

Tirando o tutorial, que eu não faço ideia de onde fica, os outros erros são traduções cobertas pela tradução do YUP. Aparentemente vc usa o Vortex né? Eu nunca usei, uso o ModOrganizer. Da uma olhada na ordem os ESM e ESPs

**Comment by JoaoManoelSilvaMorais** [comment]
> Cara, estão traduzidas aqui pra mim. Da uma olhada na ordem dos mods, pode ser que o YUP original esteja na frente da tradução.
> 
> ![image](https://user-images.githubusercontent.com/34844981/122792604-b17fd300-d290-11eb-9fe3-a06d19a49643.png)

vou ver

**Comment by MaxPresi** [comment]
Atualizei minha resposta pra ficar melhor kkkk

**Comment by JoaoManoelSilvaMorais** [comment]
Eu descobri aqui, quando o Vortex detecta que dois mods tem o mesmo arquivo ele pergunta se você quer carregar o Mod A primeiro ou o mod B, e a sua tradução estava carregando primeiro, assim o YUP original estava realmente sobrepondo sua tradução. Desconsidera os diálogos anteriores que eu postei xD

**Comment by JoaoManoelSilvaMorais** [comment]
![image](https://user-images.githubusercontent.com/85969033/122793631-d0329980-d291-11eb-85f4-f801ea3a1008.png)
Aí como está agora dps que eu corrigi

**Comment by MaxPresi** [comment]
kkkkkk na dúvida olha de novo pra ter certeza kkkkk. Ve se a porta do Victor tá com o nome certo. Vou tentar descobrir onde ficam os tutoriais.

Edit: Achei. o FormID é Helpxxxxx

Edit 2: Esse de Equipamentos também está na tradução do YUP.

**Comment by JoaoManoelSilvaMorais** [comment]
Até as armas estão traduzidas agora, e a cabana do victor tbm

**Comment by JoaoManoelSilvaMorais** [comment]
É, pode desconsiderar as prints antigas, pq foi erro meu xD

**Comment by MaxPresi** [comment]
kkkk acontece, relaxa

Foi bom que eu encontrei realmente partes sem tradução kkkkkk Vou subir uma atualização da base e do YUP.

**Comment by MaxPresi** [comment]
Atualizei lá, se puder baixar pra manter atualizado.

**Comment by JoaoManoelSilvaMorais** [comment]
> Atualizei lá, se puder baixar pra manter atualizado.

Vou atualizar

**Comment by JoaoManoelSilvaMorais** [comment]
Você mudou o nome do mod? Aqui instalou um Fallout NV e DLCs PT-BR.

edit: Mudou, agora que eu vi

**Comment by MaxPresi** [comment]
Mudei, o nome tava gigante kkkkk

**Comment by JoaoManoelSilvaMorais** [comment]
Poso criar uma aba na Guia da comunidade do jogo para divulgar o mod?

**Comment by pedricaro10** [comment]
pra mim tá traduzido

**Comment by JoaoManoelSilvaMorais** [comment]
> pra mim tá traduzido

Sim, foi um erro meu xD

**Comment by MaxPresi** [comment]
> Poso criar uma aba na Guia da comunidade do jogo para divulgar o mod?

Eu vou fazer uma quando chegar em casa. A Steam é bloqueada aqui no trabalho kkkkk

**Comment by JoaoManoelSilvaMorais** [comment]
> > Poso criar uma aba na Guia da comunidade do jogo para divulgar o mod?
> 
> Eu vou fazer uma quando chegar em casa. A Steam é bloqueada aqui no trabalho kkkkk

ok

**Comment by JoaoManoelSilvaMorais** [comment]
Johnson Nash, ultima fala
![image](https://user-images.githubusercontent.com/85969033/122846980-5aecb600-d2dd-11eb-8d84-cd846b847b3c.png)

**Comment by MaxPresi** [comment]
Era no YUP o erro, corrigi essa e outros problemas que achei. Atualizei la no Nexus.

**Comment by JoaoManoelSilvaMorais** [comment]
Não sei se com todos os médicos estão assim, mas com o de Goodsprings está:
![image](https://user-images.githubusercontent.com/85969033/123015321-779cf280-d39e-11eb-9539-b3e44b72b7c5.png)

Edit: E é a ultima versão do mod

**Comment by MaxPresi** [comment]
Amanha eu dou uma olhada

**Comment by MaxPresi** [comment]
Pronto, corrigi e atualizei lá. Era no YUP também

**Comment by JoaoManoelSilvaMorais** [comment]
Atualizei

**Comment by JoaoManoelSilvaMorais** [comment]
Aquele "Muniço" está certo?

![image](https://user-images.githubusercontent.com/85969033/123175225-cb1f4700-d457-11eb-94ac-237af4acac83.png)

Edit: Nas prints daqui para frente, pode considerar os outros patchs que vc traduziu

**Comment by MaxPresi** [comment]
Cara, parece ser a fonte original do Fallout, pela incrível qualidade de 360p kkkkkkk não tem ã nela

**Comment by JoaoManoelSilvaMorais** [comment]
Engraçado, pq os as outras partes do inventário do vendedor tem o ã, até no títulozinho ali kjkjkj, esse povo da gamevicio viu.

**Comment by pedricaro10** [comment]
Tbm os pacotes não estão traduzidos

**Comment by pedricaro10** [comment]
![ScreenShot8](https://user-images.githubusercontent.com/55963950/123358190-6809df00-d541-11eb-9f5a-9626f6cd0bae.png)
![ScreenShot9](https://user-images.githubusercontent.com/55963950/123358191-68a27580-d541-11eb-920c-272fcb9fc64c.png)
![ScreenShot10](https://user-images.githubusercontent.com/55963950/123358255-896acb00-d541-11eb-81f2-7e6551955187.png)
Oi aqui alguns erros

**Comment by MaxPresi** [comment]
Corrigido e Atualizado. YUP e a Base.
Eu não traduzi os nomes das DLCs nas mensagens de confirmação de carregamento.

**Comment by JoaoManoelSilvaMorais** [comment]
Tem coisas que é melhor no nome normal, tipo Lonesome Road, Old World Blues e Honest Hearts

**Comment by MaxPresi** [comment]
Quando são mencionadas em Diálogos e notas como uma expressão como acontece com a Lonesome Road, que coloquei como Estrada Solitária e Old World Blues que deixei como Blues do Velho Mundo.

**Comment by pedricaro10** [comment]
E o míssil?

**Comment by JoaoManoelSilvaMorais** [comment]
Ah, só traduzir para "Munição de Foguete Incendiária"

**Comment by MaxPresi** [comment]
Corrigi tbm junto. Só ver lá

**Comment by JoaoManoelSilvaMorais** [comment]
Jason Bright, é a primeira vez que eu estou interagindo com ele.
![image](https://user-images.githubusercontent.com/85969033/123700196-879d5200-d836-11eb-96b0-64d14bee0bee.png)

Agora, depois de um pouco de diálogo com ele:
![image](https://user-images.githubusercontent.com/85969033/123701219-f202c200-d837-11eb-8361-71c243fe0c34.png)

**Comment by JoaoManoelSilvaMorais** [comment]
Podia ter algum mod tipo o Darnfied UI para os terminais do jogo.
![image](https://user-images.githubusercontent.com/85969033/123703242-82420680-d83a-11eb-8451-5edc7854788f.png)

**Comment by MaxPresi** [comment]
Corrigi os diálogos, YUP atualizado no Nexus.

Acho que pra corrigir todas as fontes, acho que tem que mexer no ini, aquele mod lá não é o suficiente. EU ACHO.

**Comment by pedricaro10** [comment]
Tem ativar o loose files pra corrigi

**Comment by pedricaro10** [comment]
https://www.nexusmods.com/newvegas/mods/35935

**Comment by JoaoManoelSilvaMorais** [comment]
> Corrigi os diálogos, YUP atualizado no Nexus.
> 
> Acho que pra corrigir todas as fontes, acho que tem que mexer no ini, aquele mod lá não é o suficiente. EU ACHO.

Não funcionou editar as .ini :/
![image](https://user-images.githubusercontent.com/85969033/123722771-61d87300-d85f-11eb-80d0-53873f671146.png)

**Comment by MaxPresi** [comment]
Nem o negócio do loose files que o pedricaro10 disse?

**Comment by JoaoManoelSilvaMorais** [comment]
> Nem o negócio do loose files que o pedricaro10 disse?

Como faz isso?

Só instalar esse mod que ele mandou?

**Comment by MaxPresi** [comment]
Nem lembro como é kkkkk

**Comment by pedricaro10** [comment]
Sim e só instalar ou usar o mod organzier

**Comment by JoaoManoelSilvaMorais** [comment]
> Sim e só instalar ou usar o mod organzier

Faz tutorial aí, pq eu n uso o Mod organizer, eu uso o Vortex que é bem diferente :/
Então eu não sei usar o Mod Organizer

**Comment by MaxPresi** [comment]
Nexus caiu ou foi só pra mim?

**Comment by pedricaro10** [comment]
procura na internet tem vários

**Comment by pedricaro10** [comment]
eae
