### ISSUE TITLE
Munição de dlc e ingles

### ISSUE THREAD

**Issue by pedricaro10** [MaxPresi/FalloutNewVegas_BR#6]
Problemas na tradução na bancada de construção tem algumas muniçoes em ingles

**Comment by MaxPresi** [comment]
Cara, sem vc me mostrar o q é, fica difícil. Preciso de um print mostrando o que não está traduzido e onde.

**Comment by pedricaro10** [comment]
![enb2021_6_21_19_26_46](https://user-images.githubusercontent.com/55963950/122835768-5ddcac00-d2c7-11eb-8290-ef07ed3cf43d.png)
aqui o rocket e os nails

**Comment by pedricaro10** [comment]
tá aí screenshot

**Comment by JoaoManoelSilvaMorais** [comment]
Pior que aqui essa parte tbm não está, mas eu n sei se tem uma tradução para Nails

**Comment by MaxPresi** [comment]
Em cima de Nails é o que? Tá vazio ali

**Comment by MaxPresi** [comment]
Era na Tradução Base. Corrigi o "Nails" e outras coisas que eu achei.

**Comment by pedricaro10** [comment]
e pregos

**Comment by pedricaro10** [comment]
> Era na Tradução Base. Corrigi o "Nails" e outras coisas que eu achei.

e de uma tradução do eve eu acho
