### ISSUE TITLE
Ajuda!!!

### ISSUE THREAD

**Issue by Devius55** [MaxPresi/FalloutNewVegas_BR#7]
Eu uso o pack de mods 'Viva New Vegas' e nele tem um mod chamado 'Vanilla UI Plus' que dá conflito com o 'DarNified UI', e eu não sei o que fazer, se alguém puder me ajudar eu agradeço. ( Eu não quero ter que deletar o 'Vanilla UI plus', se possível, eu queria que eles trabalhassem juntos)

**Comment by MaxPresi** [comment]
O DarNified UI não é obrigatório, só precisa dele pra colocar o ‘ã’ mesmo. Você pode usar a tradução sem o DarNified UI.
