### ISSUE TITLE
Npcs com a boca entreaberta 

### ISSUE THREAD

**Issue by GabrielBritt** [MaxPresi/FalloutNewVegas_BR#8]
Opa, como já disse no post do nexus, parabéns pelo trabalho, isso ajuda demais a comunidade!

Gostaria de pedir ajuda com um problema: depois que os npcs falam, eles ficam com a boca entreaberta, e nunca fecham, os mods que tenho instalados são os do viva new vegas. e a tradução. quando desabilito a tradução, o problema desaparece. 
aqui estão alguns exemplos, mas acontece com todos os npcs. 

![Trudy](https://user-images.githubusercontent.com/97774467/149607855-0c58072d-08c7-4002-b92c-73d2ade43f15.png)

![chet](https://user-images.githubusercontent.com/97774467/149607857-7afd020d-02e3-4cad-ae60-0475af382293.png)

![easy pete](https://user-images.githubusercontent.com/97774467/149607858-ff2951d8-b458-4dff-9746-acc3b6060a94.png)

**Comment by MaxPresi** [comment]
Cara, nunca tive esse problema. Nem nunca ouvi falar. Eu tô viajando agora e não consigo baixar o jogo pra reproduzir o problema. O problema provavelmente é  incompatibilidade. Você instalou todos os requisitos da tradução? Instalou os mods de update?

Sent from Nine
________________________________
De: GabrielBritt ***@***.***>
Enviado: sábado, 15 de janeiro de 2022 00:56
Para: MaxPresi/FalloutNewVegas_BR
Cc: Subscribed
Assunto [MaxPresi/FalloutNewVegas_BR] Npcs com a boca entreaberta (Issue #8)

Opa, como já disse no post do nexus, parabéns pelo trabalho, isso ajuda demais a comunidade!
Gostaria de pedir ajuda com um problema: depois que os npcs falam, eles ficam com a boca entreaberta, e nunca fecham, os mods que tenho instalados são os do viva new vegas. e a tradução. quando desabilito a tradução, o problema desaparece.
aqui estão alguns exemplos, mas acontece com todos os npcs.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YsraelVB** [comment]
Comigo isso está acontecendo também. Você joga a versão pirata do GOG? Pode ser incompatibilidade com isso

**Comment by GabrielBritt** [comment]
Por incrível que pareça, não. Jogo a versão original da steam. Porém, comprei primeiro o jogo base, e depois a versão com todas as Dlcs, por isso acho que estou tendo esse problema. Mas eu simplesmente ignorei ele, e estou fazendo minha playtrought com isso mesmo. Percebi que nem todos os npcs tem esse problema, o que facilita pra eu esquecer dele as vezes.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Matheus4736** [comment]
Eu estou com esse mesmo problema, meu jogo é original Steam e segui todas as instruções para fazer instalação, estou tentando de tudo para descobrir a origem desse erro, baixei uma outra tradução e funcionou, ficaram com a boca fechada entre as falas, mas a tradução não tinha a mesma qualidade e só tem diálogos traduzidos, então tive que desistir, procurei por pessoas com mesmo problema e nada, achei que era só comigo esse erro, até olhar aqui, essa é exatamente a mesma cara de besta que meus NPC ficam fazendo kkkkk.

Antes do player interagir com o NPC ele fica normal.
![20220413173016_1](https://user-images.githubusercontent.com/103605364/163271068-cb53179e-76e1-4d23-80fe-d778f84cca86.jpg)

Mas é só iniciar o dialogo que fica com expressão bugada.
![20220413173001_1](https://user-images.githubusercontent.com/103605364/163270843-8c843bdd-e42d-4ef5-9c22-e5238ff2abc2.jpg)

Percebi também que só do NPC interagir o player a boca fica meio aberta.
![20220413173130_1](https://user-images.githubusercontent.com/103605364/163271311-2d40778a-936f-41d1-9d07-99afd00f760f.jpg)

Mas volta ao normal assim que ele faz interação com outro NPC
![20220413173427_1](https://user-images.githubusercontent.com/103605364/163271623-4237bc3c-7c65-4bb6-aab9-54a159f73cb5.jpg)

Acredito que seja algo com o modelo do rosto do NPC ao interagir com o player, vou continuar testando combinações de mods para verificar se algo em um mod especifico está causando isso. (vou postar aqui caso descubra.)

É um erro que não atrapalha em nada, tanto que já estou no final do jogo e a tradução ajuda MUITO, não estou com esperança de resolver isso sem ter que abrir mão de algum mod kkkkk
Só estou postando aqui para você saber que não está sozinho.

**Comment by MaxPresi** [comment]
Tenta testar sem as traduções do patch de correção, só com a tradução base mesmo (jogo base + dlc) e ve se resolve. Eu não consigo replicar o erro

**Comment by GabrielBritt** [comment]
Devo terminar o jogo desse jeito mesmo, depois de um tempo só aceitei que os npcs ficavam de boca aberta com minha build de carisma. ¯\_(ツ)_/¯
